# Generated by Django 4.0.2 on 2022-02-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_notification_thread'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/post_photos')),
            ],
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ManyToManyField(blank=True, to='social.ImageModel'),
        ),
    ]
