# Generated by Django 4.0.6 on 2022-07-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_imagemodel_alter_messagemodel_date_remove_post_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/profile_pictures'),
        ),
    ]
